{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ccdt.smartlife",
    "module": "WearModule",
    "version": "1.0.0-gehua",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "gehuaReleaseVariantGehuaReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "WearModule-1.0.0-gehua.aar",
          "url": "WearModule-1.0.0-gehua.aar",
          "size": 1207196,
          "sha512": "8a416e2d91fff2dd5ba51129c826f36e748e7b9ed1b3ade6f136ddc9053e1deec223495823134611f1e2e903dd19ddecb21610c9c795adb8567481ae42738903",
          "sha256": "4e68c0845a892c7e1d7bdda5179450bfc758b63bfad5754191a0dbf773472931",
          "sha1": "666bef630bd5d0c0738a9ac7665d5ab4c7d0ffcb",
          "md5": "774c4f014da208924e77dde3748475e3"
        }
      ]
    },
    {
      "name": "gehuaReleaseVariantGehuaReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.jaeger.statusbarutil",
          "module": "library",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.github.CymChad",
          "module": "BaseRecyclerViewAdapterHelper",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "com.github.mcxtzhang",
          "module": "SwipeDelMenuLayout",
          "version": {
            "requires": "V1.3.0"
          }
        },
        {
          "group": "org.eclipse.paho",
          "module": "org.eclipse.paho.client.mqttv3",
          "version": {
            "requires": "1.2.5"
          }
        },
        {
          "group": "org.eclipse.paho",
          "module": "org.eclipse.paho.android.service",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        }
      ],
      "files": [
        {
          "name": "WearModule-1.0.0-gehua.aar",
          "url": "WearModule-1.0.0-gehua.aar",
          "size": 1207196,
          "sha512": "8a416e2d91fff2dd5ba51129c826f36e748e7b9ed1b3ade6f136ddc9053e1deec223495823134611f1e2e903dd19ddecb21610c9c795adb8567481ae42738903",
          "sha256": "4e68c0845a892c7e1d7bdda5179450bfc758b63bfad5754191a0dbf773472931",
          "sha1": "666bef630bd5d0c0738a9ac7665d5ab4c7d0ffcb",
          "md5": "774c4f014da208924e77dde3748475e3"
        }
      ]
    }
  ]
}
