{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ccdt.smartlife",
    "module": "CameraModule",
    "version": "1.0.0-gehua",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "gehuaReleaseVariantGehuaReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "CameraModule-1.0.0-gehua.aar",
          "url": "CameraModule-1.0.0-gehua.aar",
          "size": 3003178,
          "sha512": "38eb32c71ab941a63372e7c072dcba21273fb773ef1fd3086a8bfb47cd596dbc44b42d5ac0697e477a246a4e15f08dc4711c4a56b6dd4f64032d46d7fc20c042",
          "sha256": "3ca643b3c48286c6f7b3d73a11e77172f0eb9687bb4d5330d6aa5b2f6ea842a1",
          "sha1": "1a55836d8f3ee0d0cda7eea166a604f7fe7b9587",
          "md5": "08feb59709d38fbf84b3f0fe34055a40"
        }
      ]
    },
    {
      "name": "gehuaReleaseVariantGehuaReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.jaeger.statusbarutil",
          "module": "library",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.github.smarxpan",
          "module": "NotchScreenTool",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "com.github.CymChad",
          "module": "BaseRecyclerViewAdapterHelper",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "com.scwang.smartrefresh",
          "module": "SmartRefreshLayout",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "com.github.zcweng",
          "module": "switch-button",
          "version": {
            "requires": "0.0.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "switch-button",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "com.contrarywind",
          "module": "Android-PickerView",
          "version": {
            "requires": "4.1.9"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        }
      ],
      "files": [
        {
          "name": "CameraModule-1.0.0-gehua.aar",
          "url": "CameraModule-1.0.0-gehua.aar",
          "size": 3003178,
          "sha512": "38eb32c71ab941a63372e7c072dcba21273fb773ef1fd3086a8bfb47cd596dbc44b42d5ac0697e477a246a4e15f08dc4711c4a56b6dd4f64032d46d7fc20c042",
          "sha256": "3ca643b3c48286c6f7b3d73a11e77172f0eb9687bb4d5330d6aa5b2f6ea842a1",
          "sha1": "1a55836d8f3ee0d0cda7eea166a604f7fe7b9587",
          "md5": "08feb59709d38fbf84b3f0fe34055a40"
        }
      ]
    }
  ]
}
