{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ccdt.smartlife",
    "module": "CameraModule",
    "version": "1.0.0-gehua",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "gehuaReleaseVariantGehuaReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "CameraModule-1.0.0-gehua.aar",
          "url": "CameraModule-1.0.0-gehua.aar",
          "size": 3002642,
          "sha512": "bcb31ae1ef476ad43041ac45818d40b6f78ba92b85d311b7d1ea887ee8c9070d06073cde861fe8ea3f26d9fece70104c6a626077217d4f87ae5ef83e9a8339fa",
          "sha256": "202822736498ea6c0a594a4ae21f0689ca3c1f4abcb33e748c4dca091a7d2bf4",
          "sha1": "7017f8f80fa0ad953dbdee9558921464136426e2",
          "md5": "6eb8a58b2a09384d4165a74458dab06c"
        }
      ]
    },
    {
      "name": "gehuaReleaseVariantGehuaReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.jaeger.statusbarutil",
          "module": "library",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.github.smarxpan",
          "module": "NotchScreenTool",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "com.github.CymChad",
          "module": "BaseRecyclerViewAdapterHelper",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "com.scwang.smartrefresh",
          "module": "SmartRefreshLayout",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "com.github.zcweng",
          "module": "switch-button",
          "version": {
            "requires": "0.0.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "switch-button",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "com.contrarywind",
          "module": "Android-PickerView",
          "version": {
            "requires": "4.1.9"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        }
      ],
      "files": [
        {
          "name": "CameraModule-1.0.0-gehua.aar",
          "url": "CameraModule-1.0.0-gehua.aar",
          "size": 3002642,
          "sha512": "bcb31ae1ef476ad43041ac45818d40b6f78ba92b85d311b7d1ea887ee8c9070d06073cde861fe8ea3f26d9fece70104c6a626077217d4f87ae5ef83e9a8339fa",
          "sha256": "202822736498ea6c0a594a4ae21f0689ca3c1f4abcb33e748c4dca091a7d2bf4",
          "sha1": "7017f8f80fa0ad953dbdee9558921464136426e2",
          "md5": "6eb8a58b2a09384d4165a74458dab06c"
        }
      ]
    }
  ]
}
