{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ccdt.smartlife",
    "module": "CameraModule",
    "version": "1.0.0-gehua",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "masterReleaseVariantMasterReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "CameraModule-1.0.0-gehua.aar",
          "url": "CameraModule-1.0.0-gehua.aar",
          "size": 3022321,
          "sha512": "7fa54bc32ce175869382fb566b114ddcbb60d7d9f190273eb3830ad2a2dd46305103cecbd535cf3b9579a1b27280c46a0d65185bc162453ff7a561ac60797fda",
          "sha256": "de60abf5b1e2e46df0ad7ff3b7ff4a05e370fdcf74e34ceb7db6e97a7d6e81e2",
          "sha1": "540e5c373034ac455474c391effcf08798670157",
          "md5": "125c76940535ed4b53a3e5e4955212c0"
        }
      ]
    },
    {
      "name": "masterReleaseVariantMasterReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.jaeger.statusbarutil",
          "module": "library",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.github.smarxpan",
          "module": "NotchScreenTool",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "com.github.CymChad",
          "module": "BaseRecyclerViewAdapterHelper",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "com.scwang.smartrefresh",
          "module": "SmartRefreshLayout",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "com.github.zcweng",
          "module": "switch-button",
          "version": {
            "requires": "0.0.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "switch-button",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "com.contrarywind",
          "module": "Android-PickerView",
          "version": {
            "requires": "4.1.9"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        }
      ],
      "files": [
        {
          "name": "CameraModule-1.0.0-gehua.aar",
          "url": "CameraModule-1.0.0-gehua.aar",
          "size": 3022321,
          "sha512": "7fa54bc32ce175869382fb566b114ddcbb60d7d9f190273eb3830ad2a2dd46305103cecbd535cf3b9579a1b27280c46a0d65185bc162453ff7a561ac60797fda",
          "sha256": "de60abf5b1e2e46df0ad7ff3b7ff4a05e370fdcf74e34ceb7db6e97a7d6e81e2",
          "sha1": "540e5c373034ac455474c391effcf08798670157",
          "md5": "125c76940535ed4b53a3e5e4955212c0"
        }
      ]
    }
  ]
}
