{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ccdt.smartlife",
    "module": "CameraModule",
    "version": "1.0.0-master",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "masterReleaseVariantMasterReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "CameraModule-1.0.0-master.aar",
          "url": "CameraModule-1.0.0-master.aar",
          "size": 3020839,
          "sha512": "c91512f06325eee238857a698bf90fde6674a43c3c56acd5f373ff5d7ab368e2c8cdf979b925e4d9718182fe712ad011e87776f9d054212b31e07aee24007338",
          "sha256": "dc55322c3d51c05e033a88c35d365ffbfcb6edc0ff81ca0c21ba19cda0db7fac",
          "sha1": "82edf46a51131b3eb05812412e79047573db99fb",
          "md5": "23aaeb32fd5a94aa048e950b368f4510"
        }
      ]
    },
    {
      "name": "masterReleaseVariantMasterReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.jaeger.statusbarutil",
          "module": "library",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.github.smarxpan",
          "module": "NotchScreenTool",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "com.github.CymChad",
          "module": "BaseRecyclerViewAdapterHelper",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "com.scwang.smartrefresh",
          "module": "SmartRefreshLayout",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "com.github.zcweng",
          "module": "switch-button",
          "version": {
            "requires": "0.0.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "switch-button",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "com.contrarywind",
          "module": "Android-PickerView",
          "version": {
            "requires": "4.1.9"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        }
      ],
      "files": [
        {
          "name": "CameraModule-1.0.0-master.aar",
          "url": "CameraModule-1.0.0-master.aar",
          "size": 3020839,
          "sha512": "c91512f06325eee238857a698bf90fde6674a43c3c56acd5f373ff5d7ab368e2c8cdf979b925e4d9718182fe712ad011e87776f9d054212b31e07aee24007338",
          "sha256": "dc55322c3d51c05e033a88c35d365ffbfcb6edc0ff81ca0c21ba19cda0db7fac",
          "sha1": "82edf46a51131b3eb05812412e79047573db99fb",
          "md5": "23aaeb32fd5a94aa048e950b368f4510"
        }
      ]
    }
  ]
}
