{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ccdt.smartlife",
    "module": "CameraModule",
    "version": "1.0.0-master",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "masterReleaseVariantMasterReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "CameraModule-1.0.0-master.aar",
          "url": "CameraModule-1.0.0-master.aar",
          "size": 3030334,
          "sha512": "b5f4598616e08e503f0c6302d76bf5845fe09534beaceeb80fa63f900d90cc2452c3976de4d9e99c0c1c1c7cc69f5e9beb914310838a0c33c94b438b724a8395",
          "sha256": "22519095a66a1b7f7d7c16cd98918955509d60d775a4f78133077877c9d383d8",
          "sha1": "e5eded15c2804a0dfadd15bbb43caf807f8a12a1",
          "md5": "a139450083f0cc582a8aeccae36827d6"
        }
      ]
    },
    {
      "name": "masterReleaseVariantMasterReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.jaeger.statusbarutil",
          "module": "library",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.github.smarxpan",
          "module": "NotchScreenTool",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "com.github.CymChad",
          "module": "BaseRecyclerViewAdapterHelper",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "com.scwang.smartrefresh",
          "module": "SmartRefreshLayout",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "com.github.zcweng",
          "module": "switch-button",
          "version": {
            "requires": "0.0.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "switch-button",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "com.contrarywind",
          "module": "Android-PickerView",
          "version": {
            "requires": "4.1.9"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        }
      ],
      "files": [
        {
          "name": "CameraModule-1.0.0-master.aar",
          "url": "CameraModule-1.0.0-master.aar",
          "size": 3030334,
          "sha512": "b5f4598616e08e503f0c6302d76bf5845fe09534beaceeb80fa63f900d90cc2452c3976de4d9e99c0c1c1c7cc69f5e9beb914310838a0c33c94b438b724a8395",
          "sha256": "22519095a66a1b7f7d7c16cd98918955509d60d775a4f78133077877c9d383d8",
          "sha1": "e5eded15c2804a0dfadd15bbb43caf807f8a12a1",
          "md5": "a139450083f0cc582a8aeccae36827d6"
        }
      ]
    }
  ]
}
