{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ccdt.smartlife",
    "module": "CameraModule",
    "version": "1.0.0-master",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "masterReleaseVariantMasterReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "CameraModule-1.0.0-master.aar",
          "url": "CameraModule-1.0.0-master.aar",
          "size": 3021427,
          "sha512": "05eacc9a3dff3d4effc369ece77399ed9afe319f47965bebff3f587218dbd84820c343f083daf58a641068d466a79eba61bfb2975b97376fcf18becd64a8afb0",
          "sha256": "fdccde9145f799683f5c8df4a31104a9ee6748e6d49dae093d4d24d9006e1835",
          "sha1": "44a3f618195e6c07730dbb4c8215dbfbc336d933",
          "md5": "112aaa7217b80eebbd8a8b678791de23"
        }
      ]
    },
    {
      "name": "masterReleaseVariantMasterReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.jaeger.statusbarutil",
          "module": "library",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.github.smarxpan",
          "module": "NotchScreenTool",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "com.github.CymChad",
          "module": "BaseRecyclerViewAdapterHelper",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "com.scwang.smartrefresh",
          "module": "SmartRefreshLayout",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "com.github.zcweng",
          "module": "switch-button",
          "version": {
            "requires": "0.0.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "switch-button",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "com.contrarywind",
          "module": "Android-PickerView",
          "version": {
            "requires": "4.1.9"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        }
      ],
      "files": [
        {
          "name": "CameraModule-1.0.0-master.aar",
          "url": "CameraModule-1.0.0-master.aar",
          "size": 3021427,
          "sha512": "05eacc9a3dff3d4effc369ece77399ed9afe319f47965bebff3f587218dbd84820c343f083daf58a641068d466a79eba61bfb2975b97376fcf18becd64a8afb0",
          "sha256": "fdccde9145f799683f5c8df4a31104a9ee6748e6d49dae093d4d24d9006e1835",
          "sha1": "44a3f618195e6c07730dbb4c8215dbfbc336d933",
          "md5": "112aaa7217b80eebbd8a8b678791de23"
        }
      ]
    }
  ]
}
